[build]
  publish = "."

[[redirects]]
  from = "/auth/x/login"
  to = "/.netlify/functions/auth-login"
  status = 200
  force = true

[[redirects]]
  from = "/auth/x/callback"
  to = "/.netlify/functions/auth-callback"
  status = 200
  force = true

[[redirects]]
  from = "/api/me"
  to = "/.netlify/functions/api-me"
  status = 200
  force = true
